export const devLatestGames = {
  count: 294,
  next: "https://api.rawg.io/api/games?dates=2026-03-01%2C2026-05-31&key=595ce12730854944a12323a753455181&ordering=-released&page=2&page_size=20",
  previous: null,
  results: [
    {
      slug: "007-first-light",
      name: "007 First Light",
      playtime: 0,
      platforms: [
        {
          platform: {
            id: 4,
            name: "PC",
            slug: "pc",
          },
        },
        {
          platform: {
            id: 187,
            name: "PlayStation 5",
            slug: "playstation5",
          },
        },
        {
          platform: {
            id: 186,
            name: "Xbox Series S/X",
            slug: "xbox-series-x",
          },
        },
        {
          platform: {
            id: 7,
            name: "Nintendo Switch",
            slug: "nintendo-switch",
          },
        },
      ],
      stores: [
        {
          store: {
            id: 1,
            name: "Steam",
            slug: "steam",
          },
        },
      ],
      released: "2026-05-27",
      tba: false,
      background_image: "https://media.rawg.io/media/games/86f/86f2dc1b9671f25a13ff92e069b51786.jpg",
      rating: 0.0,
      rating_top: 0,
      ratings: [
        {
          id: 5,
          title: "exceptional",
          count: 2,
          percent: 50.0,
        },
        {
          id: 4,
          title: "recommended",
          count: 1,
          percent: 25.0,
        },
        {
          id: 1,
          title: "skip",
          count: 1,
          percent: 25.0,
        },
      ],
      ratings_count: 1,
      reviews_text_count: 1,
      added: 179,
      added_by_status: {
        yet: 30,
        owned: 32,
        beaten: 1,
        toplay: 116,
      },
      metacritic: null,
      suggestions_count: 232,
      updated: "2026-04-15T13:56:47",
      id: 1004298,
      score: null,
      clip: null,
      tags: [],
      esrb_rating: null,
      user_game: null,
      reviews_count: 4,
      community_rating: 0,
      saturated_color: "0f0f0f",
      dominant_color: "0f0f0f",
      short_screenshots: [
        {
          id: -1,
          image: "https://media.rawg.io/media/games/86f/86f2dc1b9671f25a13ff92e069b51786.jpg",
        },
        {
          id: 4210881,
          image: "https://media.rawg.io/media/screenshots/09a/09a91ae875c2d3cc9b0d7aa73ea816bd.jpg",
        },
        {
          id: 4210892,
          image: "https://media.rawg.io/media/screenshots/234/234ec23a3478d26f066a65cf9910ec1f.jpg",
        },
        {
          id: 4210893,
          image: "https://media.rawg.io/media/screenshots/21f/21f4b318f2611d8d23dc3cbb1c3be746.jpg",
        },
        {
          id: 4210894,
          image: "https://media.rawg.io/media/screenshots/897/897d1301c75982af1489b193c8b08a1d.jpg",
        },
        {
          id: 4210895,
          image: "https://media.rawg.io/media/screenshots/490/490ccae2dcd56af896bda49422bdf5c0.jpg",
        },
      ],
      parent_platforms: [
        {
          platform: {
            id: 1,
            name: "PC",
            slug: "pc",
          },
        },
        {
          platform: {
            id: 2,
            name: "PlayStation",
            slug: "playstation",
          },
        },
        {
          platform: {
            id: 3,
            name: "Xbox",
            slug: "xbox",
          },
        },
        {
          platform: {
            id: 7,
            name: "Nintendo",
            slug: "nintendo",
          },
        },
      ],
      genres: [
        {
          id: 4,
          name: "Action",
          slug: "action",
        },
      ],
    },
    {
      slug: "lego-batman-legacy-of-the-dark-knight",
      name: "Lego Batman: Legacy of the Dark Knight",
      playtime: 0,
      platforms: [
        {
          platform: {
            id: 4,
            name: "PC",
            slug: "pc",
          },
        },
        {
          platform: {
            id: 187,
            name: "PlayStation 5",
            slug: "playstation5",
          },
        },
        {
          platform: {
            id: 186,
            name: "Xbox Series S/X",
            slug: "xbox-series-x",
          },
        },
        {
          platform: {
            id: 7,
            name: "Nintendo Switch",
            slug: "nintendo-switch",
          },
        },
      ],
      stores: [
        {
          store: {
            id: 1,
            name: "Steam",
            slug: "steam",
          },
        },
        {
          store: {
            id: 3,
            name: "PlayStation Store",
            slug: "playstation-store",
          },
        },
        {
          store: {
            id: 2,
            name: "Xbox Store",
            slug: "xbox-store",
          },
        },
        {
          store: {
            id: 6,
            name: "Nintendo Store",
            slug: "nintendo",
          },
        },
        {
          store: {
            id: 11,
            name: "Epic Games",
            slug: "epic-games",
          },
        },
      ],
      released: "2026-05-22",
      tba: false,
      background_image: "https://media.rawg.io/media/games/69a/69a6a1097f82210dbf8583f8e0d09123.jpg",
      rating: 0.0,
      rating_top: 0,
      ratings: [
        {
          id: 5,
          title: "exceptional",
          count: 1,
          percent: 50.0,
        },
        {
          id: 1,
          title: "skip",
          count: 1,
          percent: 50.0,
        },
      ],
      ratings_count: 2,
      reviews_text_count: 0,
      added: 46,
      added_by_status: {
        yet: 10,
        owned: 6,
        beaten: 1,
        toplay: 29,
      },
      metacritic: null,
      suggestions_count: 51,
      updated: "2026-03-16T20:08:40",
      id: 1009245,
      score: null,
      clip: null,
      tags: [],
      esrb_rating: {
        id: 6,
        name: "Rating Pending",
        slug: "rating-pending",
        name_en: "Rating Pending",
        name_ru: "Рейтинг обсуждается",
      },
      user_game: null,
      reviews_count: 2,
      community_rating: 0,
      saturated_color: "0f0f0f",
      dominant_color: "0f0f0f",
      short_screenshots: [
        {
          id: -1,
          image: "https://media.rawg.io/media/games/69a/69a6a1097f82210dbf8583f8e0d09123.jpg",
        },
        {
          id: 4257456,
          image: "https://media.rawg.io/media/screenshots/876/876e333fbb4862e1ba54bfff36db1e2d.jpg",
        },
      ],
      parent_platforms: [
        {
          platform: {
            id: 1,
            name: "PC",
            slug: "pc",
          },
        },
        {
          platform: {
            id: 2,
            name: "PlayStation",
            slug: "playstation",
          },
        },
        {
          platform: {
            id: 3,
            name: "Xbox",
            slug: "xbox",
          },
        },
        {
          platform: {
            id: 7,
            name: "Nintendo",
            slug: "nintendo",
          },
        },
      ],
      genres: [
        {
          id: 3,
          name: "Adventure",
          slug: "adventure",
        },
        {
          id: 4,
          name: "Action",
          slug: "action",
        },
      ],
    },
    {
      slug: "bubsy-4d",
      name: "Bubsy 4D",
      playtime: 0,
      platforms: [
        {
          platform: {
            id: 4,
            name: "PC",
            slug: "pc",
          },
        },
        {
          platform: {
            id: 187,
            name: "PlayStation 5",
            slug: "playstation5",
          },
        },
        {
          platform: {
            id: 186,
            name: "Xbox Series S/X",
            slug: "xbox-series-x",
          },
        },
        {
          platform: {
            id: 7,
            name: "Nintendo Switch",
            slug: "nintendo-switch",
          },
        },
      ],
      stores: [
        {
          store: {
            id: 5,
            name: "GOG",
            slug: "gog",
          },
        },
      ],
      released: "2026-05-21",
      tba: true,
      background_image: "https://media.rawg.io/media/screenshots/3f5/3f56e79671e3e144fefb3ad30e924c2d.jpg",
      rating: 0.0,
      rating_top: 0,
      ratings: [],
      ratings_count: 0,
      reviews_text_count: 0,
      added: 0,
      added_by_status: {},
      metacritic: null,
      suggestions_count: 45,
      updated: "2026-01-23T08:55:05",
      id: 1008989,
      score: null,
      clip: null,
      tags: [],
      esrb_rating: {
        id: 1,
        name: "Everyone",
        slug: "everyone",
        name_en: "Everyone",
        name_ru: "Для всех",
      },
      user_game: null,
      reviews_count: 0,
      community_rating: 0,
      saturated_color: "0f0f0f",
      dominant_color: "0f0f0f",
      short_screenshots: [
        {
          id: -1,
          image: "https://media.rawg.io/media/screenshots/3f5/3f56e79671e3e144fefb3ad30e924c2d.jpg",
        },
        {
          id: 4246915,
          image: "https://media.rawg.io/media/screenshots/3f5/3f56e79671e3e144fefb3ad30e924c2d.jpg",
        },
      ],
      parent_platforms: [
        {
          platform: {
            id: 1,
            name: "PC",
            slug: "pc",
          },
        },
        {
          platform: {
            id: 2,
            name: "PlayStation",
            slug: "playstation",
          },
        },
        {
          platform: {
            id: 3,
            name: "Xbox",
            slug: "xbox",
          },
        },
        {
          platform: {
            id: 7,
            name: "Nintendo",
            slug: "nintendo",
          },
        },
      ],
      genres: [
        {
          id: 83,
          name: "Platformer",
          slug: "platformer",
        },
        {
          id: 3,
          name: "Adventure",
          slug: "adventure",
        },
      ],
    },
    {
      slug: "yoshi-and-the-mysterious-book",
      name: "Yoshi and the Mysterious Book",
      playtime: 0,
      platforms: [
        {
          platform: {
            id: 7,
            name: "Nintendo Switch",
            slug: "nintendo-switch",
          },
        },
      ],
      stores: null,
      released: "2026-05-21",
      tba: false,
      background_image: "https://media.rawg.io/media/games/25a/25a256ab63823d3ed3eea8207730d074.jpg",
      rating: 0.0,
      rating_top: 0,
      ratings: [],
      ratings_count: 0,
      reviews_text_count: 0,
      added: 3,
      added_by_status: {
        yet: 2,
        owned: 1,
      },
      metacritic: null,
      suggestions_count: 0,
      updated: "2026-03-10T14:14:02",
      id: 1016114,
      score: null,
      clip: null,
      tags: [],
      esrb_rating: null,
      user_game: null,
      reviews_count: 0,
      community_rating: 0,
      saturated_color: "0f0f0f",
      dominant_color: "0f0f0f",
      short_screenshots: [
        {
          id: -1,
          image: "https://media.rawg.io/media/games/25a/25a256ab63823d3ed3eea8207730d074.jpg",
        },
      ],
      parent_platforms: [
        {
          platform: {
            id: 7,
            name: "Nintendo",
            slug: "nintendo",
          },
        },
      ],
      genres: [
        {
          id: 83,
          name: "Platformer",
          slug: "platformer",
        },
        {
          id: 3,
          name: "Adventure",
          slug: "adventure",
        },
      ],
    },
    {
      slug: "luna-abyss",
      name: "Luna Abyss",
      playtime: 0,
      platforms: [
        {
          platform: {
            id: 4,
            name: "PC",
            slug: "pc",
          },
        },
      ],
      stores: [
        {
          store: {
            id: 1,
            name: "Steam",
            slug: "steam",
          },
        },
      ],
      released: "2026-05-21",
      tba: false,
      background_image: "https://media.rawg.io/media/screenshots/1af/1afbb5ac587d61e3c93bc7d92b552f50.jpg",
      rating: 0.0,
      rating_top: 0,
      ratings: [],
      ratings_count: 0,
      reviews_text_count: 0,
      added: 21,
      added_by_status: {
        yet: 2,
        owned: 5,
        toplay: 14,
      },
      metacritic: null,
      suggestions_count: 297,
      updated: "2026-04-30T19:47:54",
      id: 846302,
      score: null,
      clip: null,
      tags: [],
      esrb_rating: null,
      user_game: null,
      reviews_count: 0,
      community_rating: 0,
      saturated_color: "0f0f0f",
      dominant_color: "0f0f0f",
      short_screenshots: [
        {
          id: -1,
          image: "https://media.rawg.io/media/screenshots/1af/1afbb5ac587d61e3c93bc7d92b552f50.jpg",
        },
        {
          id: 3551203,
          image: "https://media.rawg.io/media/screenshots/147/1473c3b6fa75f338a5dc6322d209e004.jpg",
        },
        {
          id: 3551204,
          image: "https://media.rawg.io/media/screenshots/b4e/b4e86b026e975d3f70422bf8245f0da2.jpg",
        },
        {
          id: 3551205,
          image: "https://media.rawg.io/media/screenshots/363/363706543223b69fa9a6fab5df00b2ba.jpg",
        },
        {
          id: 3551206,
          image: "https://media.rawg.io/media/screenshots/aa7/aa7c50baac2f0ff945598159f8f9487a.jpg",
        },
        {
          id: 3551207,
          image: "https://media.rawg.io/media/screenshots/1af/1afbb5ac587d61e3c93bc7d92b552f50.jpg",
        },
      ],
      parent_platforms: [
        {
          platform: {
            id: 1,
            name: "PC",
            slug: "pc",
          },
        },
      ],
      genres: [
        {
          id: 3,
          name: "Adventure",
          slug: "adventure",
        },
        {
          id: 4,
          name: "Action",
          slug: "action",
        },
      ],
    },
    {
      slug: "zero-parades-for-dead-spies",
      name: "ZERO PARADES: For Dead Spies",
      playtime: 0,
      platforms: [
        {
          platform: {
            id: 4,
            name: "PC",
            slug: "pc",
          },
        },
      ],
      stores: [
        {
          store: {
            id: 5,
            name: "GOG",
            slug: "gog",
          },
        },
      ],
      released: "2026-05-20",
      tba: false,
      background_image: "https://media.rawg.io/media/screenshots/c86/c86f732afb067a071a46293c65833fa3.jpg",
      rating: 0.0,
      rating_top: 0,
      ratings: [],
      ratings_count: 0,
      reviews_text_count: 0,
      added: 2,
      added_by_status: {
        yet: 1,
        toplay: 1,
      },
      metacritic: null,
      suggestions_count: 0,
      updated: "2026-04-24T14:36:22",
      id: 1017366,
      score: null,
      clip: null,
      tags: [
        {
          id: 820,
          name: "secrets",
          slug: "secrets",
          language: "eng",
          games_count: 3437,
          image_background: "https://media.rawg.io/media/screenshots/8c2/8c2ca7679b364a63bf690647fcf35481.jpg",
        },
        {
          id: 5033,
          name: "tv",
          slug: "tv",
          language: "eng",
          games_count: 550,
          image_background: "https://media.rawg.io/media/screenshots/e67/e678a2ae9019399d5f989c9b3babefd7.jpg",
        },
        {
          id: 2838,
          name: "jet",
          slug: "jet",
          language: "eng",
          games_count: 362,
          image_background: "https://media.rawg.io/media/screenshots/6ee/6ee93371e46ebfe5b042d4d7494ac879.jpg",
        },
        {
          id: 92375,
          name: "Jeu de rôle",
          slug: "jeu-de-role-2",
          language: "eng",
          games_count: 26,
          image_background: "https://media.rawg.io/media/screenshots/ade/adec7e438a624578f6deb9c67950c1b9.jpg",
        },
        {
          id: 7337,
          name: "c",
          slug: "c",
          language: "eng",
          games_count: 3078,
          image_background: "https://media.rawg.io/media/screenshots/12c/12cb921a1090905bf6fa42eea4300588.jpg",
        },
        {
          id: 4787,
          name: "disco",
          slug: "disco",
          language: "eng",
          games_count: 152,
          image_background: "https://media.rawg.io/media/screenshots/42c/42c0d592de2e9c7ee8c4e71901a7024e.jpg",
        },
        {
          id: 2360,
          name: "stress",
          slug: "stress",
          language: "eng",
          games_count: 234,
          image_background: "https://media.rawg.io/media/screenshots/a3a/a3a2eeb52cf328c37e05f678f70ca994.jpg",
        },
      ],
      esrb_rating: null,
      user_game: null,
      reviews_count: 0,
      community_rating: 0,
      saturated_color: "0f0f0f",
      dominant_color: "0f0f0f",
      short_screenshots: [
        {
          id: -1,
          image: "https://media.rawg.io/media/screenshots/c86/c86f732afb067a071a46293c65833fa3.jpg",
        },
        {
          id: 4304216,
          image: "https://media.rawg.io/media/screenshots/db3/db35576dfaf5f94f3a3e934d274f019a.jpg",
        },
        {
          id: 4304217,
          image: "https://media.rawg.io/media/screenshots/8f5/8f5eb4864d1452f1f86b097f148b514c.jpg",
        },
        {
          id: 4304218,
          image: "https://media.rawg.io/media/screenshots/f4a/f4a8f6ba3fa2e69e19e46073b6b765cd.jpg",
        },
        {
          id: 4304219,
          image: "https://media.rawg.io/media/screenshots/68e/68e2cb81e98f7c554d51884694e3ae32.jpg",
        },
        {
          id: 4304220,
          image: "https://media.rawg.io/media/screenshots/d26/d262c718996defa60ffb21f3db65854c.jpg",
        },
        {
          id: 4304221,
          image: "https://media.rawg.io/media/screenshots/420/4204e511f70ca09df01759f07b3264b7.jpg",
        },
      ],
      parent_platforms: [
        {
          platform: {
            id: 1,
            name: "PC",
            slug: "pc",
          },
        },
      ],
      genres: [],
    },
    {
      slug: "coffee-talk-tokyo",
      name: "Coffee Talk Tokyo",
      playtime: 0,
      platforms: [
        {
          platform: {
            id: 4,
            name: "PC",
            slug: "pc",
          },
        },
      ],
      stores: [
        {
          store: {
            id: 5,
            name: "GOG",
            slug: "gog",
          },
        },
      ],
      released: "2026-05-20",
      tba: false,
      background_image: "https://media.rawg.io/media/screenshots/8ee/8eed3221af05ce5dc058bc1ecf148695.jpg",
      rating: 0.0,
      rating_top: 0,
      ratings: [],
      ratings_count: 0,
      reviews_text_count: 0,
      added: 0,
      added_by_status: null,
      metacritic: null,
      suggestions_count: 0,
      updated: "2026-02-09T11:39:26",
      id: 1015932,
      score: null,
      clip: null,
      tags: [
        {
          id: 1009,
          name: "chill",
          slug: "chill",
          language: "eng",
          games_count: 941,
          image_background: "https://media.rawg.io/media/screenshots/106/106d1708f07538971825954678011e24.jpeg",
        },
        {
          id: 92376,
          name: "Aventure",
          slug: "aventure",
          language: "eng",
          games_count: 26,
          image_background: "https://media.rawg.io/media/screenshots/375/375ccacac093b9fde0ad82ebb021b483.jpg",
        },
      ],
      esrb_rating: null,
      user_game: null,
      reviews_count: 0,
      community_rating: 0,
      saturated_color: "0f0f0f",
      dominant_color: "0f0f0f",
      short_screenshots: [
        {
          id: -1,
          image: "https://media.rawg.io/media/screenshots/8ee/8eed3221af05ce5dc058bc1ecf148695.jpg",
        },
        {
          id: 4298919,
          image: "https://media.rawg.io/media/screenshots/bf1/bf1dee44537a68eb293deb0f57173ad7.jpg",
        },
        {
          id: 4298920,
          image: "https://media.rawg.io/media/screenshots/9f1/9f1c4f1bacd9c7e86a433492a1092095.jpg",
        },
        {
          id: 4298921,
          image: "https://media.rawg.io/media/screenshots/933/9332c5818d6f0063f48bf737f1273324.jpg",
        },
        {
          id: 4298922,
          image: "https://media.rawg.io/media/screenshots/6ee/6eecc594f3dc02f0f91bc68b5a143a60.jpg",
        },
        {
          id: 4298923,
          image: "https://media.rawg.io/media/screenshots/8ee/8eed3221af05ce5dc058bc1ecf148695.jpg",
        },
      ],
      parent_platforms: [
        {
          platform: {
            id: 1,
            name: "PC",
            slug: "pc",
          },
        },
      ],
      genres: [],
    },
    {
      slug: "phonopolis",
      name: "Phonopolis",
      playtime: 0,
      platforms: [
        {
          platform: {
            id: 4,
            name: "PC",
            slug: "pc",
          },
        },
        {
          platform: {
            id: 5,
            name: "macOS",
            slug: "macos",
          },
        },
      ],
      stores: [
        {
          store: {
            id: 5,
            name: "GOG",
            slug: "gog",
          },
        },
      ],
      released: "2026-05-20",
      tba: false,
      background_image: "https://media.rawg.io/media/games/044/044e2732dc470c41a6a2ac074bdf7fb0.jpg",
      rating: 0.0,
      rating_top: 0,
      ratings: [
        {
          id: 5,
          title: "exceptional",
          count: 1,
          percent: 100.0,
        },
      ],
      ratings_count: 0,
      reviews_text_count: 1,
      added: 14,
      added_by_status: {
        yet: 3,
        toplay: 10,
        playing: 1,
      },
      metacritic: null,
      suggestions_count: 96,
      updated: "2026-04-30T10:17:38",
      id: 275607,
      score: null,
      clip: null,
      tags: [
        {
          id: 1709,
          name: "work",
          slug: "work",
          language: "eng",
          games_count: 9300,
          image_background: "https://media.rawg.io/media/games/bd2/bd2cc7714e0b9b1adad1ba1b2400d436.jpg",
        },
        {
          id: 3068,
          name: "future",
          slug: "future",
          language: "eng",
          games_count: 3146,
          image_background: "https://media.rawg.io/media/screenshots/7f2/7f280778b23561fe3ea8ffa04d5ed61f.jpg",
        },
        {
          id: 740,
          name: "demo",
          slug: "demo",
          language: "eng",
          games_count: 4404,
          image_background: "https://media.rawg.io/media/games/00f/00f411107c447a6fc9623e18c4f39e7c.jpg",
        },
        {
          id: 690,
          name: "paper",
          slug: "paper",
          language: "eng",
          games_count: 1547,
          image_background: "https://media.rawg.io/media/screenshots/bb3/bb30d5157a8ef647192d10140eabc7b6.jpg",
        },
      ],
      esrb_rating: null,
      user_game: null,
      reviews_count: 1,
      community_rating: 0,
      saturated_color: "0f0f0f",
      dominant_color: "0f0f0f",
      short_screenshots: [
        {
          id: -1,
          image: "https://media.rawg.io/media/games/044/044e2732dc470c41a6a2ac074bdf7fb0.jpg",
        },
        {
          id: 1771636,
          image: "https://media.rawg.io/media/screenshots/806/806558b7c005600e18e0d6e4de18af77.jpg",
        },
        {
          id: 1771637,
          image: "https://media.rawg.io/media/screenshots/aa3/aa3c89975d2a3a160e13c7ba12385a5b.jpg",
        },
        {
          id: 1771638,
          image: "https://media.rawg.io/media/screenshots/089/0894347e351aa509077c67e2e54dab0c.jpg",
        },
      ],
      parent_platforms: [
        {
          platform: {
            id: 1,
            name: "PC",
            slug: "pc",
          },
        },
        {
          platform: {
            id: 5,
            name: "Apple Macintosh",
            slug: "mac",
          },
        },
      ],
      genres: [
        {
          id: 3,
          name: "Adventure",
          slug: "adventure",
        },
      ],
    },
    {
      slug: "forza-horizon-6",
      name: "Forza Horizon 6",
      playtime: 0,
      platforms: [
        {
          platform: {
            id: 4,
            name: "PC",
            slug: "pc",
          },
        },
        {
          platform: {
            id: 186,
            name: "Xbox Series S/X",
            slug: "xbox-series-x",
          },
        },
      ],
      stores: null,
      released: "2026-05-19",
      tba: false,
      background_image: "https://media.rawg.io/media/games/d74/d744a3b0f6f0f0bc63f5ceb9b5e63230.jpeg",
      rating: 0.0,
      rating_top: 0,
      ratings: [
        {
          id: 1,
          title: "skip",
          count: 1,
          percent: 100.0,
        },
      ],
      ratings_count: 1,
      reviews_text_count: 0,
      added: 61,
      added_by_status: {
        yet: 19,
        owned: 12,
        beaten: 1,
        toplay: 28,
        playing: 1,
      },
      metacritic: null,
      suggestions_count: 82,
      updated: "2026-02-24T17:21:28",
      id: 1010949,
      score: null,
      clip: null,
      tags: [],
      esrb_rating: null,
      user_game: null,
      reviews_count: 1,
      community_rating: 0,
      saturated_color: "0f0f0f",
      dominant_color: "0f0f0f",
      short_screenshots: [
        {
          id: -1,
          image: "https://media.rawg.io/media/games/d74/d744a3b0f6f0f0bc63f5ceb9b5e63230.jpeg",
        },
        {
          id: 4297968,
          image: "https://media.rawg.io/media/screenshots/a93/a93f2a8ec0d112b5514cfdea70e02941.jpg",
        },
        {
          id: 4297969,
          image: "https://media.rawg.io/media/screenshots/e55/e552184cae79bdccfe6fc4e0bef0eff6.jpg",
        },
        {
          id: 4297970,
          image: "https://media.rawg.io/media/screenshots/4b3/4b31d3f63fd0f14775cb9aa9c867f546.jpg",
        },
        {
          id: 4297971,
          image: "https://media.rawg.io/media/screenshots/b6c/b6ce385dcbc719779964af47d9f15010.jpg",
        },
        {
          id: 4297972,
          image: "https://media.rawg.io/media/screenshots/aa4/aa41094e34080e189ad219b7d4da23cd.jpg",
        },
      ],
      parent_platforms: [
        {
          platform: {
            id: 1,
            name: "PC",
            slug: "pc",
          },
        },
        {
          platform: {
            id: 3,
            name: "Xbox",
            slug: "xbox",
          },
        },
      ],
      genres: [
        {
          id: 1,
          name: "Racing",
          slug: "racing",
        },
      ],
    },
    {
      slug: "corsairs-battle-of-the-caribbean",
      name: "Corsairs - Battle of the Caribbean",
      playtime: 0,
      platforms: [
        {
          platform: {
            id: 4,
            name: "PC",
            slug: "pc",
          },
        },
      ],
      stores: [
        {
          store: {
            id: 5,
            name: "GOG",
            slug: "gog",
          },
        },
      ],
      released: "2026-05-17",
      tba: false,
      background_image: "https://media.rawg.io/media/screenshots/ac0/ac0157a39c43d49bf2662e441f9a1322.jpg",
      rating: 0.0,
      rating_top: 0,
      ratings: [],
      ratings_count: 0,
      reviews_text_count: 0,
      added: 1,
      added_by_status: {
        toplay: 1,
      },
      metacritic: null,
      suggestions_count: 206,
      updated: "2026-02-06T11:07:18",
      id: 961807,
      score: null,
      clip: null,
      tags: [
        {
          id: 1465,
          name: "combat",
          slug: "combat",
          language: "eng",
          games_count: 16368,
          image_background: "https://media.rawg.io/media/screenshots/120/120d930368bc171c42f9caab94e33c65.jpg",
        },
        {
          id: 67,
          name: "Management",
          slug: "management",
          language: "eng",
          games_count: 9396,
          image_background: "https://media.rawg.io/media/screenshots/e70/e7009d889b38df2a16f78859a7343308.jpg",
        },
        {
          id: 981,
          name: "battle",
          slug: "battle",
          language: "eng",
          games_count: 10704,
          image_background: "https://media.rawg.io/media/games/075/0753492cda7ee3c9bd4a3ca673fd0c8c.jpg",
        },
        {
          id: 581,
          name: "Epic",
          slug: "epic",
          language: "eng",
          games_count: 4136,
          image_background: "https://media.rawg.io/media/screenshots/671/6716b656707c65cdf21882ee51b4f2ff.jpg",
        },
        {
          id: 1529,
          name: "fight",
          slug: "fight",
          language: "eng",
          games_count: 7925,
          image_background: "https://media.rawg.io/media/games/174/1743b3dd185bda4a7be349347d4064df.jpg",
        },
        {
          id: 245,
          name: "Trading",
          slug: "trading",
          language: "eng",
          games_count: 1490,
          image_background: "https://media.rawg.io/media/screenshots/8ba/8ba023119cc83dff0d1d535f12e6b348.jpg",
        },
        {
          id: 1221,
          name: "history",
          slug: "history",
          language: "eng",
          games_count: 2390,
          image_background: "https://media.rawg.io/media/games/cdd/cdd4b6cf03ac7ebf7460b0d82f9aaa09.jpg",
        },
        {
          id: 2232,
          name: "journey",
          slug: "journey",
          language: "eng",
          games_count: 2122,
          image_background: "https://media.rawg.io/media/screenshots/10e/10e169bb13e65551a0ab7127a83585df.jpg",
        },
        {
          id: 894,
          name: "Classes",
          slug: "classes",
          language: "eng",
          games_count: 1031,
          image_background: "https://media.rawg.io/media/games/4da/4da63441cb94d7adb4d954871b65db30.jpg",
        },
        {
          id: 18426,
          name: "enemy",
          slug: "enemy",
          language: "eng",
          games_count: 2588,
          image_background: "https://media.rawg.io/media/screenshots/b3b/b3b69e92cc30ffeea9ee230c954fa49a.jpg",
        },
        {
          id: 2546,
          name: "ships",
          slug: "ships",
          language: "eng",
          games_count: 1570,
          image_background: "https://media.rawg.io/media/screenshots/6e9/6e998e7948054270676c3e50422ecec1.jpg",
        },
        {
          id: 3718,
          name: "effects",
          slug: "effects",
          language: "eng",
          games_count: 477,
          image_background: "https://media.rawg.io/media/screenshots/849/84923f6107bb95ee631c31905edb153f.jpg",
        },
        {
          id: 4949,
          name: "defend",
          slug: "defend",
          language: "eng",
          games_count: 105,
          image_background: "https://media.rawg.io/media/screenshots/f6a/f6a625a3fad31f575db617ab0a8b2bd5.jpg",
        },
      ],
      esrb_rating: null,
      user_game: null,
      reviews_count: 0,
      community_rating: 0,
      saturated_color: "0f0f0f",
      dominant_color: "0f0f0f",
      short_screenshots: [
        {
          id: -1,
          image: "https://media.rawg.io/media/screenshots/ac0/ac0157a39c43d49bf2662e441f9a1322.jpg",
        },
        {
          id: 3893082,
          image: "https://media.rawg.io/media/screenshots/058/058516d7d2757abc6ae6b5b4f3f644ad.jpg",
        },
        {
          id: 3893083,
          image: "https://media.rawg.io/media/screenshots/57f/57f61c718d09b047849172eab76190a7.jpg",
        },
        {
          id: 3893084,
          image: "https://media.rawg.io/media/screenshots/fda/fda3c0ba344e2f60642886bb5da80ad3.jpg",
        },
        {
          id: 3893085,
          image: "https://media.rawg.io/media/screenshots/4f9/4f951a3dae46a544a8d982588413ecf8.jpg",
        },
        {
          id: 3893086,
          image: "https://media.rawg.io/media/screenshots/ac0/ac0157a39c43d49bf2662e441f9a1322.jpg",
        },
      ],
      parent_platforms: [
        {
          platform: {
            id: 1,
            name: "PC",
            slug: "pc",
          },
        },
      ],
      genres: [],
    },
    {
      slug: "outbound",
      name: "Outbound",
      playtime: 0,
      platforms: null,
      stores: null,
      released: "2026-05-14",
      tba: false,
      background_image: "https://media.rawg.io/media/games/851/851cf64d1e55bc8f98e617bc38d7f5f2.jpg",
      rating: 0.0,
      rating_top: 0,
      ratings: [],
      ratings_count: 0,
      reviews_text_count: 0,
      added: 3,
      added_by_status: {
        yet: 1,
        owned: 1,
        toplay: 1,
      },
      metacritic: null,
      suggestions_count: 0,
      updated: "2026-04-25T14:09:48",
      id: 1016307,
      score: null,
      clip: null,
      tags: [],
      esrb_rating: null,
      user_game: null,
      reviews_count: 0,
      community_rating: 0,
      saturated_color: "0f0f0f",
      dominant_color: "0f0f0f",
      short_screenshots: [
        {
          id: -1,
          image: "https://media.rawg.io/media/games/851/851cf64d1e55bc8f98e617bc38d7f5f2.jpg",
        },
      ],
      genres: [
        {
          id: 3,
          name: "Adventure",
          slug: "adventure",
        },
      ],
    },
    {
      slug: "clockwork-ambrosia",
      name: "Clockwork Ambrosia",
      playtime: 0,
      platforms: [
        {
          platform: {
            id: 4,
            name: "PC",
            slug: "pc",
          },
        },
      ],
      stores: [
        {
          store: {
            id: 1,
            name: "Steam",
            slug: "steam",
          },
        },
      ],
      released: "2026-05-12",
      tba: false,
      background_image: "https://media.rawg.io/media/screenshots/3ef/3ef0787f01a9fd890ff7949fb49f8a8f.jpg",
      rating: 0.0,
      rating_top: 0,
      ratings: [],
      ratings_count: 0,
      reviews_text_count: 0,
      added: 1,
      added_by_status: {
        yet: 1,
      },
      metacritic: null,
      suggestions_count: 0,
      updated: "2026-04-21T20:29:19",
      id: 1017352,
      score: null,
      clip: null,
      tags: null,
      esrb_rating: null,
      user_game: null,
      reviews_count: 0,
      community_rating: 0,
      saturated_color: "0f0f0f",
      dominant_color: "0f0f0f",
      short_screenshots: [
        {
          id: -1,
          image: "https://media.rawg.io/media/screenshots/3ef/3ef0787f01a9fd890ff7949fb49f8a8f.jpg",
        },
        {
          id: 4304173,
          image: "https://media.rawg.io/media/screenshots/3ef/3ef0787f01a9fd890ff7949fb49f8a8f.jpg",
        },
      ],
      parent_platforms: [
        {
          platform: {
            id: 1,
            name: "PC",
            slug: "pc",
          },
        },
      ],
      genres: [
        {
          id: 51,
          name: "Indie",
          slug: "indie",
        },
        {
          id: 3,
          name: "Adventure",
          slug: "adventure",
        },
        {
          id: 4,
          name: "Action",
          slug: "action",
        },
      ],
    },
    {
      slug: "the-dark-pictures-directive-8020",
      name: "Directive 8020",
      playtime: 0,
      platforms: [
        {
          platform: {
            id: 4,
            name: "PC",
            slug: "pc",
          },
        },
        {
          platform: {
            id: 187,
            name: "PlayStation 5",
            slug: "playstation5",
          },
        },
        {
          platform: {
            id: 186,
            name: "Xbox Series S/X",
            slug: "xbox-series-x",
          },
        },
      ],
      stores: [
        {
          store: {
            id: 1,
            name: "Steam",
            slug: "steam",
          },
        },
        {
          store: {
            id: 3,
            name: "PlayStation Store",
            slug: "playstation-store",
          },
        },
        {
          store: {
            id: 2,
            name: "Xbox Store",
            slug: "xbox-store",
          },
        },
      ],
      released: "2026-05-12",
      tba: false,
      background_image: "https://media.rawg.io/media/games/10d/10dd957940dbaedc77a08730995194c7.jpg",
      rating: 2.33,
      rating_top: 1,
      ratings: [
        {
          id: 1,
          title: "skip",
          count: 5,
          percent: 55.56,
        },
        {
          id: 4,
          title: "recommended",
          count: 4,
          percent: 44.44,
        },
      ],
      ratings_count: 7,
      reviews_text_count: 0,
      added: 143,
      added_by_status: {
        yet: 25,
        owned: 26,
        beaten: 1,
        toplay: 91,
      },
      metacritic: null,
      suggestions_count: 206,
      updated: "2026-03-14T14:48:13",
      id: 881141,
      score: null,
      clip: null,
      tags: [],
      esrb_rating: null,
      user_game: null,
      reviews_count: 9,
      saturated_color: "0f0f0f",
      dominant_color: "0f0f0f",
      short_screenshots: [
        {
          id: -1,
          image: "https://media.rawg.io/media/games/10d/10dd957940dbaedc77a08730995194c7.jpg",
        },
        {
          id: 3651766,
          image: "https://media.rawg.io/media/screenshots/5a4/5a4f2fd68784a50a2f474f9e4c57f680.jpg",
        },
        {
          id: 4160066,
          image: "https://media.rawg.io/media/screenshots/802/802d04b6880ab531008e1ad80ef4e4ec.jpg",
        },
        {
          id: 4160067,
          image: "https://media.rawg.io/media/screenshots/91a/91ae3a4ed650a666c33e137f1d7fac3d.jpg",
        },
        {
          id: 4160068,
          image: "https://media.rawg.io/media/screenshots/ac8/ac809d41fa6b70332f25c1494108e61c.jpg",
        },
        {
          id: 4160069,
          image: "https://media.rawg.io/media/screenshots/3ec/3ec5930aa01a46844a7da1bfec6b9799.jpg",
        },
      ],
      parent_platforms: [
        {
          platform: {
            id: 1,
            name: "PC",
            slug: "pc",
          },
        },
        {
          platform: {
            id: 2,
            name: "PlayStation",
            slug: "playstation",
          },
        },
        {
          platform: {
            id: 3,
            name: "Xbox",
            slug: "xbox",
          },
        },
      ],
      genres: [
        {
          id: 3,
          name: "Adventure",
          slug: "adventure",
        },
        {
          id: 4,
          name: "Action",
          slug: "action",
        },
      ],
    },
    {
      slug: "uncle-lees-cookbook-five-recipes-for-disaster",
      name: "Uncle Lee’s Cookbook: Five Recipes for Disaster",
      playtime: 0,
      platforms: [
        {
          platform: {
            id: 4,
            name: "PC",
            slug: "pc",
          },
        },
      ],
      stores: [
        {
          store: {
            id: 5,
            name: "GOG",
            slug: "gog",
          },
        },
      ],
      released: "2026-05-11",
      tba: false,
      background_image: "https://media.rawg.io/media/screenshots/b32/b32dd3a1e02fa4651f46fce4a308f798.jpg",
      rating: 0.0,
      rating_top: 0,
      ratings: [],
      ratings_count: 0,
      reviews_text_count: 0,
      added: 0,
      added_by_status: null,
      metacritic: null,
      suggestions_count: 0,
      updated: "2026-05-01T18:04:03",
      id: 1017633,
      score: null,
      clip: null,
      tags: [
        {
          id: 138,
          name: "Relaxing",
          slug: "relaxing",
          language: "eng",
          games_count: 21538,
          image_background: "https://media.rawg.io/media/games/f86/f869253c68b38fa789f58cc5be2cb996.jpg",
        },
        {
          id: 1867,
          name: "puzzles",
          slug: "puzzles",
          language: "eng",
          games_count: 8882,
          image_background: "https://media.rawg.io/media/games/9e5/9e5b25a276f9248c36c0fd78288738ce.jpg",
        },
        {
          id: 295,
          name: "Soundtrack",
          slug: "soundtrack",
          language: "eng",
          games_count: 3307,
          image_background: "https://media.rawg.io/media/games/872/8721094b44212218051621bc6fbee27d.jpg",
        },
        {
          id: 87,
          name: "Science",
          slug: "science",
          language: "eng",
          games_count: 2009,
          image_background: "https://media.rawg.io/media/games/174/1743b3dd185bda4a7be349347d4064df.jpg",
        },
        {
          id: 2595,
          name: "click",
          slug: "click",
          language: "eng",
          games_count: 11246,
          image_background: "https://media.rawg.io/media/screenshots/0f2/0f24fa93c032771a26da862296cbc2b5.jpg",
        },
        {
          id: 1986,
          name: "ice",
          slug: "ice",
          language: "eng",
          games_count: 2177,
          image_background: "https://media.rawg.io/media/screenshots/82f/82f152cf71e5055a4119363998efd13c.jpg",
        },
        {
          id: 92376,
          name: "Aventure",
          slug: "aventure",
          language: "eng",
          games_count: 84,
          image_background: "https://media.rawg.io/media/games/12d/12d20a8e023ba98bc0b88de86ad0193b.jpg",
        },
        {
          id: 3584,
          name: "characters",
          slug: "characters",
          language: "eng",
          games_count: 1323,
          image_background: "https://media.rawg.io/media/games/37c/37c521e41bf65943389ebe4a6cb00b14.jpg",
        },
        {
          id: 1310,
          name: "machine",
          slug: "machine",
          language: "eng",
          games_count: 861,
          image_background: "https://media.rawg.io/media/screenshots/399/3999efe49d9eac11b6fedd14f7d67c3c.jpg",
        },
        {
          id: 758,
          name: "challenging",
          slug: "challenging",
          language: "eng",
          games_count: 1085,
          image_background: "https://media.rawg.io/media/screenshots/646/646082643dadbb48287d979fe15ad81d.jpg",
        },
        {
          id: 1699,
          name: "town",
          slug: "town",
          language: "eng",
          games_count: 753,
          image_background: "https://media.rawg.io/media/games/69b/69bb7cc65186b07978fd173138bb02ad.jpg",
        },
        {
          id: 3583,
          name: "book",
          slug: "book",
          language: "eng",
          games_count: 320,
          image_background: "https://media.rawg.io/media/games/15b/15b8dfa78091b549baa744597e49edd3.jpg",
        },
        {
          id: 3187,
          name: "break",
          slug: "break",
          language: "eng",
          games_count: 416,
          image_background: "https://media.rawg.io/media/screenshots/4a2/4a2335783245b74eb5ef7f08ff634cbe.jpg",
        },
        {
          id: 1816,
          name: "birthday",
          slug: "birthday",
          language: "eng",
          games_count: 238,
          image_background: "https://media.rawg.io/media/screenshots/a65/a6575ae87bbd395bcdb3881a090e1694.jpg",
        },
        {
          id: 3750,
          name: "quantum",
          slug: "quantum",
          language: "eng",
          games_count: 74,
          image_background: "https://media.rawg.io/media/screenshots/d2b/d2ba0582079181a0ce8764a5840ce960.jpg",
        },
      ],
      esrb_rating: null,
      user_game: null,
      reviews_count: 0,
      community_rating: 0,
      saturated_color: "0f0f0f",
      dominant_color: "0f0f0f",
      short_screenshots: [
        {
          id: -1,
          image: "https://media.rawg.io/media/screenshots/b32/b32dd3a1e02fa4651f46fce4a308f798.jpg",
        },
        {
          id: 4305586,
          image: "https://media.rawg.io/media/screenshots/772/7723bdcbcd0fb5a1f5071dfe6b85899b.jpg",
        },
        {
          id: 4305587,
          image: "https://media.rawg.io/media/screenshots/fed/fed768dd2eabf8e06902475d11ba9c2f.jpg",
        },
        {
          id: 4305588,
          image: "https://media.rawg.io/media/screenshots/66c/66c24f6d05c1cda5bec4bdab34920324.jpg",
        },
        {
          id: 4305589,
          image: "https://media.rawg.io/media/screenshots/29a/29a737018c663252721b7692f4ea9ac2.jpg",
        },
        {
          id: 4305590,
          image: "https://media.rawg.io/media/screenshots/c3d/c3d6fb9175617fa888d2c0052e0b2705.jpg",
        },
        {
          id: 4305591,
          image: "https://media.rawg.io/media/screenshots/36f/36f6ef710ead43376ff66c16c4b3c435.jpg",
        },
      ],
      parent_platforms: [
        {
          platform: {
            id: 1,
            name: "PC",
            slug: "pc",
          },
        },
      ],
      genres: [],
    },
    {
      slug: "battlestar-galactica-scattered-hopes",
      name: "Battlestar Galactica: Scattered Hopes",
      playtime: 0,
      platforms: [
        {
          platform: {
            id: 4,
            name: "PC",
            slug: "pc",
          },
        },
      ],
      stores: [
        {
          store: {
            id: 5,
            name: "GOG",
            slug: "gog",
          },
        },
      ],
      released: "2026-05-10",
      tba: true,
      background_image: "https://media.rawg.io/media/screenshots/84d/84d2168586f372e40fe68f17e1a70c5b.jpg",
      rating: 0.0,
      rating_top: 0,
      ratings: [],
      ratings_count: 0,
      reviews_text_count: 0,
      added: 1,
      added_by_status: {
        toplay: 1,
      },
      metacritic: null,
      suggestions_count: 0,
      updated: "2026-05-01T18:07:52",
      id: 1008990,
      score: null,
      clip: null,
      tags: [
        {
          id: 92377,
          name: "Stratégie",
          slug: "strategie-2",
          language: "eng",
          games_count: 20,
          image_background: "https://media.rawg.io/media/screenshots/5ec/5ecbd6bf5844b1a0ef2c6167891590ba.jpg",
        },
      ],
      esrb_rating: null,
      user_game: null,
      reviews_count: 0,
      community_rating: 0,
      saturated_color: "0f0f0f",
      dominant_color: "0f0f0f",
      short_screenshots: [
        {
          id: -1,
          image: "https://media.rawg.io/media/screenshots/84d/84d2168586f372e40fe68f17e1a70c5b.jpg",
        },
        {
          id: 4305609,
          image: "https://media.rawg.io/media/screenshots/1b0/1b0fed6092f49f0c6ed6de01806c2fb0.jpg",
        },
        {
          id: 4305610,
          image: "https://media.rawg.io/media/screenshots/306/3064929a0411cf000c1df4baebd5989b.jpg",
        },
        {
          id: 4305611,
          image: "https://media.rawg.io/media/screenshots/50b/50ba88c936531e1cf24b9c3e93507660.jpg",
        },
        {
          id: 4305612,
          image: "https://media.rawg.io/media/screenshots/dd0/dd0aa9ea99ec6e71dcba2badfdbd7b58.jpg",
        },
        {
          id: 4305613,
          image: "https://media.rawg.io/media/screenshots/4c2/4c2146db27ec2dee7ee433cab6487aa6.jpg",
        },
        {
          id: 4305614,
          image: "https://media.rawg.io/media/screenshots/62a/62adb60dae746aa2b308a9542ec12070.jpg",
        },
      ],
      parent_platforms: [
        {
          platform: {
            id: 1,
            name: "PC",
            slug: "pc",
          },
        },
      ],
      genres: [
        {
          id: 10,
          name: "Strategy",
          slug: "strategy",
        },
      ],
    },
    {
      slug: "mixtape-2025",
      name: "Mixtape (2025)",
      playtime: 0,
      platforms: [
        {
          platform: {
            id: 4,
            name: "PC",
            slug: "pc",
          },
        },
        {
          platform: {
            id: 187,
            name: "PlayStation 5",
            slug: "playstation5",
          },
        },
        {
          platform: {
            id: 186,
            name: "Xbox Series S/X",
            slug: "xbox-series-x",
          },
        },
      ],
      stores: [
        {
          store: {
            id: 1,
            name: "Steam",
            slug: "steam",
          },
        },
      ],
      released: "2026-05-07",
      tba: false,
      background_image: "https://media.rawg.io/media/screenshots/2e1/2e1a19d938c0e7a4a396924125923c38.jpg",
      rating: 0.0,
      rating_top: 0,
      ratings: [],
      ratings_count: 0,
      reviews_text_count: 0,
      added: 33,
      added_by_status: {
        yet: 2,
        owned: 4,
        toplay: 27,
      },
      metacritic: null,
      suggestions_count: 173,
      updated: "2026-03-03T17:43:01",
      id: 983374,
      score: null,
      clip: null,
      tags: [],
      esrb_rating: {
        id: 6,
        name: "Rating Pending",
        slug: "rating-pending",
        name_en: "Rating Pending",
        name_ru: "Рейтинг обсуждается",
      },
      user_game: null,
      reviews_count: 0,
      community_rating: 0,
      saturated_color: "0f0f0f",
      dominant_color: "0f0f0f",
      short_screenshots: [
        {
          id: -1,
          image: "https://media.rawg.io/media/screenshots/2e1/2e1a19d938c0e7a4a396924125923c38.jpg",
        },
        {
          id: 4053743,
          image: "https://media.rawg.io/media/screenshots/274/27489e9d2eeb610210bb3cbd54128235.jpg",
        },
        {
          id: 4053744,
          image: "https://media.rawg.io/media/screenshots/be2/be2d57e6ac10871ba5dd7efe6a51abd6.jpg",
        },
        {
          id: 4053745,
          image: "https://media.rawg.io/media/screenshots/5fb/5fbd580868b81f3e98df98292a5c8659.jpg",
        },
        {
          id: 4053746,
          image: "https://media.rawg.io/media/screenshots/2e1/2e1a19d938c0e7a4a396924125923c38.jpg",
        },
      ],
      parent_platforms: [
        {
          platform: {
            id: 1,
            name: "PC",
            slug: "pc",
          },
        },
        {
          platform: {
            id: 2,
            name: "PlayStation",
            slug: "playstation",
          },
        },
        {
          platform: {
            id: 3,
            name: "Xbox",
            slug: "xbox",
          },
        },
      ],
      genres: [
        {
          id: 51,
          name: "Indie",
          slug: "indie",
        },
        {
          id: 3,
          name: "Adventure",
          slug: "adventure",
        },
      ],
    },
    {
      slug: "mixtape",
      name: "Mixtape",
      playtime: 0,
      platforms: [
        {
          platform: {
            id: 4,
            name: "PC",
            slug: "pc",
          },
        },
      ],
      stores: null,
      released: "2026-05-07",
      tba: false,
      background_image: "https://media.rawg.io/media/games/a57/a571fcbc2b2ef30fb3e13a4272ef3a93.jpeg",
      rating: 0.0,
      rating_top: 0,
      ratings: [],
      ratings_count: 0,
      reviews_text_count: 0,
      added: 7,
      added_by_status: {
        yet: 3,
        owned: 1,
        toplay: 3,
      },
      metacritic: null,
      suggestions_count: 97,
      updated: "2026-03-20T17:11:03",
      id: 103715,
      score: null,
      clip: null,
      tags: [],
      esrb_rating: null,
      user_game: null,
      reviews_count: 0,
      community_rating: 0,
      saturated_color: "0f0f0f",
      dominant_color: "0f0f0f",
      short_screenshots: [
        {
          id: -1,
          image: "https://media.rawg.io/media/games/a57/a571fcbc2b2ef30fb3e13a4272ef3a93.jpeg",
        },
      ],
      parent_platforms: [
        {
          platform: {
            id: 1,
            name: "PC",
            slug: "pc",
          },
        },
      ],
      genres: [
        {
          id: 3,
          name: "Adventure",
          slug: "adventure",
        },
      ],
    },
    {
      slug: "will-follow-the-light",
      name: "Will: Follow the Light",
      playtime: 0,
      platforms: null,
      stores: null,
      released: "2026-05-07",
      tba: false,
      background_image: "https://media.rawg.io/media/games/300/3001ccfd69be0255b346e1b03269008c.jpg",
      rating: 0.0,
      rating_top: 0,
      ratings: [],
      ratings_count: 0,
      reviews_text_count: 0,
      added: 3,
      added_by_status: {
        yet: 1,
        toplay: 2,
      },
      metacritic: null,
      suggestions_count: 0,
      updated: "2026-04-30T10:21:06",
      id: 1016316,
      score: null,
      clip: null,
      tags: [],
      esrb_rating: null,
      user_game: null,
      reviews_count: 0,
      community_rating: 0,
      saturated_color: "0f0f0f",
      dominant_color: "0f0f0f",
      short_screenshots: [
        {
          id: -1,
          image: "https://media.rawg.io/media/games/300/3001ccfd69be0255b346e1b03269008c.jpg",
        },
      ],
      genres: [
        {
          id: 3,
          name: "Adventure",
          slug: "adventure",
        },
      ],
    },
    {
      slug: "motorslice",
      name: "MOTORSLICE",
      playtime: 0,
      platforms: [
        {
          platform: {
            id: 4,
            name: "PC",
            slug: "pc",
          },
        },
      ],
      stores: [
        {
          store: {
            id: 1,
            name: "Steam",
            slug: "steam",
          },
        },
        {
          store: {
            id: 5,
            name: "GOG",
            slug: "gog",
          },
        },
      ],
      released: "2026-05-05",
      tba: false,
      background_image: "https://media.rawg.io/media/screenshots/781/781e814ff47631b425e8f4136804d95f.jpg",
      rating: 0.0,
      rating_top: 0,
      ratings: [],
      ratings_count: 0,
      reviews_text_count: 0,
      added: 5,
      added_by_status: {
        yet: 2,
        owned: 2,
        toplay: 1,
      },
      metacritic: null,
      suggestions_count: 19,
      updated: "2026-04-30T19:54:16",
      id: 1002696,
      score: null,
      clip: null,
      tags: [
        {
          id: 13,
          name: "Atmospheric",
          slug: "atmospheric",
          language: "eng",
          games_count: 39708,
          image_background: "https://media.rawg.io/media/games/f46/f466571d536f2e3ea9e815ad17177501.jpg",
        },
        {
          id: 69,
          name: "Action-Adventure",
          slug: "action-adventure",
          language: "eng",
          games_count: 21027,
          image_background: "https://media.rawg.io/media/games/7f6/7f6cd70ba2ad57053b4847c13569f2d8.jpg",
        },
        {
          id: 134,
          name: "Anime",
          slug: "anime",
          language: "eng",
          games_count: 17067,
          image_background: "https://media.rawg.io/media/games/c88/c88463dcf1b3fc79c54a59c30076344a.jpg",
        },
        {
          id: 188,
          name: "Parkour",
          slug: "parkour",
          language: "eng",
          games_count: 4105,
          image_background: "https://media.rawg.io/media/games/341/3413d7275fb1e919f00a925df8288b77.jpg",
        },
      ],
      esrb_rating: {
        id: 4,
        name: "Mature",
        slug: "mature",
        name_en: "Mature",
        name_ru: "С 17 лет",
      },
      user_game: null,
      reviews_count: 0,
      community_rating: 0,
      saturated_color: "0f0f0f",
      dominant_color: "0f0f0f",
      short_screenshots: [
        {
          id: -1,
          image: "https://media.rawg.io/media/screenshots/781/781e814ff47631b425e8f4136804d95f.jpg",
        },
        {
          id: 4198812,
          image: "https://media.rawg.io/media/screenshots/7fe/7fe9ee4338e257a1f00d727b5756f5ad.jpg",
        },
        {
          id: 4198813,
          image: "https://media.rawg.io/media/screenshots/f1c/f1c41a119d3359903250c819dfff278e.jpg",
        },
        {
          id: 4198814,
          image: "https://media.rawg.io/media/screenshots/353/353239274a7ed5f76c2ebbb60af23939.jpg",
        },
        {
          id: 4198815,
          image: "https://media.rawg.io/media/screenshots/b27/b277254d32d736e1d684596cb24a0e4a.jpg",
        },
        {
          id: 4198816,
          image: "https://media.rawg.io/media/screenshots/e40/e40f5f853c9d8675120678af72aecdc1.jpg",
        },
        {
          id: 4198817,
          image: "https://media.rawg.io/media/screenshots/667/66755b959fa3fe7ca638a829b92f3535.jpg",
        },
      ],
      parent_platforms: [
        {
          platform: {
            id: 1,
            name: "PC",
            slug: "pc",
          },
        },
      ],
      genres: [
        {
          id: 51,
          name: "Indie",
          slug: "indie",
        },
        {
          id: 3,
          name: "Adventure",
          slug: "adventure",
        },
        {
          id: 4,
          name: "Action",
          slug: "action",
        },
      ],
    },
    {
      slug: "charm-studies-2",
      name: "Charm Studies",
      playtime: 0,
      platforms: [
        {
          platform: {
            id: 4,
            name: "PC",
            slug: "pc",
          },
        },
        {
          platform: {
            id: 5,
            name: "macOS",
            slug: "macos",
          },
        },
        {
          platform: {
            id: 6,
            name: "Linux",
            slug: "linux",
          },
        },
      ],
      stores: [
        {
          store: {
            id: 1,
            name: "Steam",
            slug: "steam",
          },
        },
      ],
      released: "2026-04-30",
      tba: false,
      background_image: "https://media.rawg.io/media/screenshots/345/345ced68a5275127e67aca02c37f9559.jpg",
      rating: 0.0,
      rating_top: 0,
      ratings: [],
      ratings_count: 0,
      reviews_text_count: 0,
      added: 0,
      added_by_status: null,
      metacritic: null,
      suggestions_count: 0,
      updated: "2026-05-01T18:01:02",
      id: 1017632,
      score: null,
      clip: null,
      tags: [
        {
          id: 31,
          name: "Singleplayer",
          slug: "singleplayer",
          language: "eng",
          games_count: 250928,
          image_background: "https://media.rawg.io/media/games/511/5118aff5091cb3efec399c808f8c598f.jpg",
        },
        {
          id: 42396,
          name: "Для одного игрока",
          slug: "dlia-odnogo-igroka",
          language: "rus",
          games_count: 70775,
          image_background: "https://media.rawg.io/media/games/bc0/bc06a29ceac58652b684deefe7d56099.jpg",
        },
        {
          id: 40847,
          name: "Steam Achievements",
          slug: "steam-achievements",
          language: "eng",
          games_count: 51765,
          image_background: "https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg",
        },
        {
          id: 42398,
          name: "Инди",
          slug: "indi-2",
          language: "rus",
          games_count: 68803,
          image_background: "https://media.rawg.io/media/games/63f/63f0e68688cad279ed38cde931dbfcdb.jpg",
        },
        {
          id: 42394,
          name: "Глубокий сюжет",
          slug: "glubokii-siuzhet",
          language: "rus",
          games_count: 18131,
          image_background: "https://media.rawg.io/media/games/6c5/6c55e22185876626881b76c11922b073.jpg",
        },
        {
          id: 118,
          name: "Story Rich",
          slug: "story-rich",
          language: "eng",
          games_count: 27274,
          image_background: "https://media.rawg.io/media/games/7a2/7a2500ee8b2c0e1ff268bb4479463dea.jpg",
        },
        {
          id: 42399,
          name: "Казуальная игра",
          slug: "kazualnaia-igra",
          language: "rus",
          games_count: 54966,
          image_background: "https://media.rawg.io/media/games/594/59487800889ebac294c7c2c070d02356.jpg",
        },
        {
          id: 45,
          name: "2D",
          slug: "2d",
          language: "eng",
          games_count: 207810,
          image_background: "https://media.rawg.io/media/games/f3e/f3eec35c6218dcfd93a537751e6bfa61.jpg",
        },
        {
          id: 42465,
          name: "Головоломка",
          slug: "golovolomka",
          language: "rus",
          games_count: 21597,
          image_background: "https://media.rawg.io/media/screenshots/c97/c97b943741f5fbc936fe054d9d58851d.jpg",
        },
        {
          id: 189,
          name: "Female Protagonist",
          slug: "female-protagonist",
          language: "eng",
          games_count: 15557,
          image_background: "https://media.rawg.io/media/games/3cf/3cff89996570cf29a10eb9cd967dcf73.jpg",
        },
        {
          id: 42407,
          name: "Аниме",
          slug: "anime-2",
          language: "rus",
          games_count: 12942,
          image_background: "https://media.rawg.io/media/screenshots/12e/12ee2600684863837596c0dbb1923fca.jpg",
        },
        {
          id: 134,
          name: "Anime",
          slug: "anime",
          language: "eng",
          games_count: 17075,
          image_background: "https://media.rawg.io/media/games/9fb/9fbf956a16249def7625ab5dc3d09515.jpg",
        },
        {
          id: 42586,
          name: "Милая",
          slug: "milaia",
          language: "rus",
          games_count: 18884,
          image_background: "https://media.rawg.io/media/games/eb5/eb514db62d397c64288160d5bd8fd67a.jpg",
        },
        {
          id: 42601,
          name: "Цветастая",
          slug: "tsvetastaia",
          language: "rus",
          games_count: 20407,
          image_background: "https://media.rawg.io/media/games/e74/e74458058b35e01c1ae3feeb39a3f724.jpg",
        },
        {
          id: 88,
          name: "Cute",
          slug: "cute",
          language: "eng",
          games_count: 39806,
          image_background: "https://media.rawg.io/media/games/f15/f15e1dbda32b588a981bbc6b222a4b4c.jpg",
        },
        {
          id: 165,
          name: "Colorful",
          slug: "colorful",
          language: "eng",
          games_count: 28962,
          image_background: "https://media.rawg.io/media/games/fc8/fc838d98c9b944e6a15176eabf40bee8.jpg",
        },
        {
          id: 82,
          name: "Magic",
          slug: "magic",
          language: "eng",
          games_count: 11357,
          image_background: "https://media.rawg.io/media/games/bfb/bfb2bf7a0413443b1fcf0be7c3244053.jpg",
        },
        {
          id: 42564,
          name: "Расслабляющая",
          slug: "rasslabliaiushchaia",
          language: "rus",
          games_count: 13840,
          image_background: "https://media.rawg.io/media/games/c49/c4983df94a8a8167d652b812de742da8.jpg",
        },
        {
          id: 42478,
          name: "Магия",
          slug: "magiia",
          language: "rus",
          games_count: 5984,
          image_background: "https://media.rawg.io/media/games/044/044b2ee023930ca138deda151f40c18c.jpg",
        },
        {
          id: 42393,
          name: "Визуальная новелла",
          slug: "vizualnaia-novella",
          language: "rus",
          games_count: 10139,
          image_background: "https://media.rawg.io/media/games/b2c/b2c9c6115114c8f7d461b5430e8a7d4a.jpg",
        },
        {
          id: 90,
          name: "Visual Novel",
          slug: "visual-novel",
          language: "eng",
          games_count: 10000,
          image_background: "https://media.rawg.io/media/games/f0a/f0a65d7d9c4534f8f4897f9d161307ed.jpg",
        },
        {
          id: 138,
          name: "Relaxing",
          slug: "relaxing",
          language: "eng",
          games_count: 21538,
          image_background: "https://media.rawg.io/media/games/f86/f869253c68b38fa789f58cc5be2cb996.jpg",
        },
        {
          id: 305,
          name: "Linear",
          slug: "linear",
          language: "eng",
          games_count: 9751,
          image_background: "https://media.rawg.io/media/games/736/736c0eaec96d848d7824b33298a182f2.jpg",
        },
        {
          id: 42437,
          name: "Линейная",
          slug: "lineinaia",
          language: "rus",
          games_count: 9694,
          image_background: "https://media.rawg.io/media/games/9af/9af24c1886e2c7b52a4a2c65aa874638.jpg",
        },
        {
          id: 91686,
          name: "Family Sharing",
          slug: "family-sharing",
          language: "eng",
          games_count: 29004,
          image_background: "https://media.rawg.io/media/games/942/9424d6bb763dc38d9378b488603c87fa.jpg",
        },
        {
          id: 59643,
          name: "Протагонистка",
          slug: "protagonistka",
          language: "eng",
          games_count: 8028,
          image_background: "https://media.rawg.io/media/screenshots/234/2341a78cfc68acd460228fafcf7f9ccc.jpg",
        },
        {
          id: 42410,
          name: "LGBTQ+",
          slug: "lgbtq-2",
          language: "eng",
          games_count: 2771,
          image_background: "https://media.rawg.io/media/games/fbd/fbd0128013b7965904be571e75fb30c0.jpg",
        },
        {
          id: 42700,
          name: "Логика",
          slug: "logika",
          language: "rus",
          games_count: 5579,
          image_background: "https://media.rawg.io/media/screenshots/066/066eb1b7a3f332b8089645fbf8c3ebdc.jpg",
        },
        {
          id: 575,
          name: "Logic",
          slug: "logic",
          language: "eng",
          games_count: 6321,
          image_background: "https://media.rawg.io/media/games/89c/89ceadfd42109aa0d80e9c5dbc86f277.jpg",
        },
        {
          id: 59756,
          name: "ЛГБТК+",
          slug: "lgbtk",
          language: "rus",
          games_count: 2423,
          image_background: "https://media.rawg.io/media/games/154/1540d92a4768230fe46bfd05954b8ab4.jpg",
        },
        {
          id: 92227,
          name: "Custom Volume Controls",
          slug: "custom-volume-controls",
          language: "eng",
          games_count: 3334,
          image_background: "https://media.rawg.io/media/games/e7f/e7f2f571761abd7b3c0598c719ae8893.jpg",
        },
        {
          id: 92225,
          name: "Playable without Timed Input",
          slug: "playable-without-timed-input",
          language: "eng",
          games_count: 3343,
          image_background: "https://media.rawg.io/media/screenshots/128/12863c97d6d6e21b94b1a9d879efe8e0.jpg",
        },
        {
          id: 92226,
          name: "Save Anytime",
          slug: "save-anytime",
          language: "eng",
          games_count: 1838,
          image_background: "https://media.rawg.io/media/games/2cb/2cb70f855efdec3476bf927b61cdd502.jpg",
        },
        {
          id: 92232,
          name: "Keyboard Only Option",
          slug: "keyboard-only-option",
          language: "eng",
          games_count: 1088,
          image_background: "https://media.rawg.io/media/screenshots/720/720a0c8e51c1467e06f7476a5553f51c.jpg",
        },
        {
          id: 92229,
          name: "Mouse Only Option",
          slug: "mouse-only-option",
          language: "eng",
          games_count: 1607,
          image_background: "https://media.rawg.io/media/screenshots/80f/80f42aff93e9e52faf204425963c5088.jpg",
        },
      ],
      esrb_rating: null,
      user_game: null,
      reviews_count: 0,
      community_rating: 0,
      saturated_color: "0f0f0f",
      dominant_color: "0f0f0f",
      short_screenshots: [
        {
          id: -1,
          image: "https://media.rawg.io/media/screenshots/345/345ced68a5275127e67aca02c37f9559.jpg",
        },
        {
          id: 4305581,
          image: "https://media.rawg.io/media/screenshots/e30/e30677ab5b14081611ecb24805f9d10f.jpg",
        },
        {
          id: 4305582,
          image: "https://media.rawg.io/media/screenshots/250/250cf41b1210a89d33e0f65fe5c0aed5.jpg",
        },
        {
          id: 4305583,
          image: "https://media.rawg.io/media/screenshots/d1b/d1b751e02ae2fddfeac5b4e1238fed06.jpg",
        },
        {
          id: 4305584,
          image: "https://media.rawg.io/media/screenshots/c4b/c4b49cb39b784c29907269706c960c18.jpg",
        },
        {
          id: 4305585,
          image: "https://media.rawg.io/media/screenshots/345/345ced68a5275127e67aca02c37f9559.jpg",
        },
      ],
      parent_platforms: [
        {
          platform: {
            id: 1,
            name: "PC",
            slug: "pc",
          },
        },
        {
          platform: {
            id: 5,
            name: "Apple Macintosh",
            slug: "mac",
          },
        },
        {
          platform: {
            id: 6,
            name: "Linux",
            slug: "linux",
          },
        },
      ],
      genres: [
        {
          id: 40,
          name: "Casual",
          slug: "casual",
        },
        {
          id: 51,
          name: "Indie",
          slug: "indie",
        },
      ],
    },
  ],
  user_platforms: false,
};
